
<?php   $this->layout("layout1.phtml");?>

					<p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-md visible-lg"><br></p>
                    <h2>Here you can</h2>					
                    <h2>improve your</h2>
					<h2>active vocabulary</h2>
                    <p class="row visible-sm visible-md visible-lg"><br></p>
                    <h3>To start, select a word group</h3>
                    <h3>by clicking the image</h3>
				</div>
				<div class="col-md-6">
                    <p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-sm visible-md visible-lg"><br></p>
                    <div data-ride="carousel" class="carousel slide" id="myCarousel1">
                        <div id="myCarousel1PlaceHolder" class="carousel-inner">
                        <?php
                        $aCategories = $this->data["categories"];
                        $nCategories = count($aCategories);
                        $aWords = $this->data["words"];
                        $nWords = count($aWords);                                                 
                        $indexCategory = 0;
                        for($i = 0; $i < $nCategories; $i++)
                        {
                            $indexCategory = $i;                            
                            $oCategory = $aCategories[$i];
                            $categoryID = $oCategory->ID;
                            // Build an array for all words that belong to the same category
                            $aWordIDs = array();
                            for($j = 0; $j < $nWords; $j++)
                            {
                                $oWord = $aWords[$j];
                                if ( $oWord->categoryID == $categoryID )
                                {
                                    array_push($aWordIDs,$oWord->ID);
                                }
                            }
                            
                            // Randomly shuffle the words array
                            $nArraySize = count($aWordIDs);
                            $aTemporaryArray = array();
                            for ($x = $nArraySize-1 ; $x >= 0; $x--) {
                                $nRandomIndex = rand(0, $x);
                                array_push($aTemporaryArray, $aWordIDs[$nRandomIndex]);
                                array_splice($aWordIDs, $nRandomIndex, 1);
                            }                            
                            $aWordIDs = $aTemporaryArray;
                            
                            $nNextWordID = array_pop($aWordIDs);
                            $sWordIDs = implode(",",$aWordIDs);?>                        
                            
                            <div class="item<?php if($i == 0) echo " active"; ?>">
                                <a href="/words/<?php echo $nNextWordID ?>/<?php echo $sWordIDs ?>">
                                    <img class="imgcarousel1" alt="<?php echo $oCategory->name ?>" src="/<?php echo $oCategory->image; ?>" title="<?php echo $oCategory->name ?>">
                                    <p class="imgcaptioncarousel1"><?php echo $oCategory->name ?></p>
                                </a>
                            </div>
                        <?php
                        } ?>
                        </div>
                        <a data-slide="prev" href="#myCarousel1" class="left carousel-control"><i class="fa fa-arrow-left"></i></a>
                        <a data-slide="next" href="#myCarousel1" class="right carousel-control"><i class="fa fa-arrow-right"></i></a>
                        <script>
                            jQuery("document").ready(function() {
                                jQuery("#myCarousel1").carousel({
                                    interval : 3000
                                });
                            });
                        </script>
				    </div>
                </div>
            </div>

