		<header class="container">
			<nav class="row">
				<ul>
					<li class="col-sm-3"><a href="/">HOME</a></li>
					<li class="col-sm-3 visible-sm visible-md visible-lg"><a href="/topdeals">TOP DEALS</a></li>
					<li class="col-sm-3 visible-sm visible-md visible-lg"><a href="/about">ABOUT US</a></li>
					<li class="col-sm-3 visible-sm visible-md visible-lg"><a href="/contact">CONTACT US</a></li>
				</ul>
			</nav>
		</header>
