
<?php   $this->layout("_layout_.phtml");?>

                        <?php
                        $oWord = $this->data["word"];?>

					<p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-md visible-lg"><br></p>
                    <h2>Here you can</h2>					
                    <h2>improve your</h2>
					<h2>active vocabulary <?php echo $oWord->word ?></h2>
                    <p class="row visible-sm visible-md visible-lg"><br></p>
                    <h3>To start, select a word group</h3>
                    <h3>by clicking the image</h3>
				</div>

                <div class="col-md-6">
                    <p class="row visible-sm visible-md visible-lg"><br></p>
					<p class="row visible-sm visible-md visible-lg"><br></p>
                    <div class="row visible-sm visible-md visible-lg">
                        <img class="imgcarousel1" alt="<?php echo $oWord->word ?>" src="/<?php echo $oWord->imageURL; ?>" title="<?php echo $oWord->word ?>">
                    </div>
                </div>
            </div>

